# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6.6']

    steps:
    - uses: actions/checkout@v2

    - name: InfluxDB Action
      # You may pin to the exact commit or the version.
      # uses: russorat/influxdb-action@285d1a28cef338a1945853697a1d7558806b70a5
      uses: TheHolyRoger/influxdb-action@main
      with:
        # Sets the version of InfluxDB to use (for example: 2.0.7). See https://portal.influxdata.com/downloads/ for versions. latest and nightly are also supported.
        influxdb_version: v1
        # Set to false if you only need to use the cli tools without a locally running InfluxDB instance. If this is false, you can ignore the init parameters.
        influxdb_start: true # optional, default is true
        # The initial Organization of the InfluxDB instance.
        influxdb_org: influxdata # optional, default is organization
        # The initial User of the InfluxDB instance.
        influxdb_user: root # optional, default is user
        # The initial Password of the InfluxDB instance.
        influxdb_password: rootroot # optional, default is password
        # The initial Bucket of the InfluxDB instance.
        influxdb_bucket: peatio_test # optional, default is bucket
